### ISSUE TITLE
Got error on Windows OS

### ISSUE THREAD

**Issue by shivapoudel** [fdaciuk/hoost#2]
Windows Users don't have host file in `/etc/hosts` xD
![capture](https://cloud.githubusercontent.com/assets/3774827/9050058/1ea9baf2-3a69-11e5-9cba-5104459877cc.PNG)

**Comment by fdaciuk** [comment]
@shivapoudel yes, I know that :(
This feature will be implemented in a future release.
But this is already in my roadmap ;)

I'd be glad with a pull request ;)

By the way, Do you know the path to "hosts" file on Windows (all releases)?
Could you send me?

**Comment by shivapoudel** [comment]
@fdaciuk this is the path for all hosts file in Windows OS`C:\Windows\System32\drivers\etc\hosts`

**Comment by fdaciuk** [comment]
Nice! I think you can change the Windows' installation path, right? Thus, it is better to use `%SYSTEMROOT%\drivers\etc\hosts` (or something like that) to point for the right path :)

**Comment by shivapoudel** [comment]
@fdaciuk we should use `%SYSTEMROOT%\system32\drivers\etc\hosts`. Does we can set that path for hoost anywhere :P

**Comment by fdaciuk** [comment]
We can use this file: https://github.com/fdaciuk/hoost/blob/master/lib/host-file.js
Add [`os` package](https://nodejs.org/api/os.html#os_os_platform) and verify by  `os.plataform()` ;)

**Comment by shivapoudel** [comment]
@fdaciuk Fixed for Windows Platform via #3 xD

**Comment by shivapoudel** [comment]
@fdaciuk ping :)

**Comment by fdaciuk** [comment]
Thanks :smile:
