### ISSUE TITLE
Inquirer confirm prompt looped for multiple times

### ISSUE THREAD

**Issue by shivapoudel** [fdaciuk/hoost#4]
While editing hoost I found this inquirer confirm prompt looped for multiple times ;)
![capture](https://cloud.githubusercontent.com/assets/3774827/9075791/d3357068-3b38-11e5-94e0-a14be86b85ee.PNG)

Try to edit hoost and go on pressing `y`, you will figure out :)

**Comment by fdaciuk** [comment]
Really weird! You tested on another system or just on Windows?

**Comment by shivapoudel** [comment]
@fdaciuk only on Windows :)

**Comment by shivapoudel** [comment]
@fdaciuk did you figure out the bug?

**Comment by fdaciuk** [comment]
Hey @shivapoudel! I released a new version a few days ago. In Ubuntu, this works fine. Could you test on Windows again, with the new version, and send me a feedback?

**Comment by shivapoudel** [comment]
Yep this has been fixed :+1:

**Comment by fdaciuk** [comment]
Niiice!! Thanks a lot! :dancer: :dancer: :sparkles:
